AWSTemplateFormatVersion: 2010-09-09
Resources:
  DevEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-00c39f71452c08778
      InstanceType: t2.micro
      KeyName: cfkey
      SecurityGroups:
        - Ref: MySSHSGTest
      Tags:
        - Key: Name
          Value: Ec2DemoTest
        - Key: Environment
          Value: Test

  MySSHSGTest:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
