AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SSHKeyName: 
    Description: AWS SSH Key Name to use in Ec2 Instance
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: cfkey
  AvailabilityZone:
    Description: Availability zone for ec2
    Type: String
    Default: us-east-1a

Resources:
  DevEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-00c39f71452c08778
      InstanceType: t2.micro
      KeyName: !Ref SSHKeyName
      AvailabilityZone:
         Ref:  AvailabilityZone

      Tags:
        - Key: Name
          Value: Ec2DemoTest
        - Key: Environment
          Value: Test
